[package]
name = "srd-editor"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "srd-editor"

[dependencies]
iced = { version = "0.14.0", default-features = false, features = ["canvas", "image", "tokio", "wayland", "wgpu", "x11"] }
image_dds = { version = "0.7.2", default-features = false }
lucide-icons = { version = "1.28.0", features = ["iced"] }
png = "0.18.0"
pollster = "0.4.0"
rfd = { version = "0.16.0", default-features = false, features = ["xdg-portal", "tokio"] }
wgpu = "27.0.1"
